import { ChevronLeft } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import LogoCatshop from '@/public/LogoCatshop.png'
import 'animate.css';
import { ReturnBack } from "@/components/button/ReturnBack";

export const metadata = {
   title: "ShopCat",
   description: "Generated by create next app",
};

export default function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
   return (
      <div className="min-h-dvh w-[90%] m-auto space-y-10" >

         <header className="bg-bgMenu basis-[30%] rounded-lg mt-4 p-2">
            <Link href={'/'}>
               <Image className="cursor-pointer"
                  src={LogoCatshop}
                  alt="Logo"
                  width={100}
               />
            </Link>
         </header>
         <ReturnBack/>
         <main className="overflow-hidden w-full">
            {children}
         </main>

      </div>
   );

}