import { ChevronLeft } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import LogoCatshop from '@/public/LogoCatshop.png'
import 'animate.css';


export const metadata = {
   title: "ShopCat",
   description: "Generated by create next app",
};

export default function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
   return (
      <div className="min-h-dvh w-[90%] m-auto space-y-5" >

         <header className="bg-bgMenu basis-[30%] rounded-lg mt-4 p-2">
            <Link href={'/'}>
               <Image className="cursor-pointer"
                  src={LogoCatshop}
                  alt="Logo"
                  width={100}
               />
            </Link>
         </header>

         <Link className="w-fit block" href={'/shop'}>
            <button className="align-middle">
               <ChevronLeft fontSize={50} strokeWidth={3} />
            </button>
            <span className="align-middle font-medium text-lg md:text-xl">Volver</span>
         </Link>

         <main className="overflow-hidden w-full">
            {children}
         </main>

      </div>
   );

}